.TH ASNDISC 1 2012-06-24 NCBI "NCBI Tools User's Manual"
.SH NAME
asndisc \- check ASN.1 biological sequence records for discrepancies
.SH SYNOPSIS
.B asndisc
[\|\fB\-\fP\|]
[\|\fB\-B\fP\|]
[\|\fB\-C\fP\ \fIN\fP\|]
[\|\fB\-F\fP\|]
[\|\fB\-I\fP\ \fIpath\fP\|]
[\|\fB\-L\fP\ \fIstr\fP\|]
[\|\fB\-N\fP\ \fIfilename\fP\|]
[\|\fB\-P\fP\ \fIstr\fP\|]
[\|\fB\-R\fP\|]
[\|\fB\-S\fP\|]
[\|\fB\-T\fP\|]
[\|\fB\-X\fP\ \fItests\fP\|]
[\|\fB\-Z\fP\|]
[\|\fB\-a\fP\ \fIstr\fP\|]
[\|\fB\-b\fP\|]
[\|\fB\-c\fP\|]
[\|\fB\-d\fP\ \fItests\fP\|]
[\|\fB\-e\fP\ \fItests\fP\|]
[\|\fB\-f\fP\|]
[\|\fB\-i\fP\ \fIfilename\fP\|]
[\|\fB\-k\fP\|]
[\|\fB\-l\fP\|]
[\|\fB\-o\fP\ \fIfilename\fP\|]
[\|\fB\-p\fP\ \fIpath\fP\|]
[\|\fB\-r\fP\ \fIdir\fP\|]
[\|\fB\-s\fP\ \fIext\fP\|]
[\|\fB\-t\fP\|]
[\|\fB\-u\fP\|]
[\|\fB\-w\fP\ \fIfilename\fP\|]
[\|\fB\-x\fP\ \fIstr\fP\|]
.SH DESCRIPTION
\fBasndisc\fP is a command-line tool to check ASN.1-format biological
sequence records for discrepancies.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-B\fP
Big sequence report
.TP
\fB\-C\fP\ \fIN\fP
Max count
.TP
\fB\-F\fP
Fix product name list
.TP
\fB\-I\fP\ \fIpath\fP
Path to Indexed binary ASN.1 data
.TP
\fB\-L\fP\ \fIstr\fP
Lineage to use
.TP
\fB\-N\fP\ \fIfilename\fP
File with list of product names to check
.TP
\fB\-P\fP\ \fIstr\fP
RePort type
.RS
.PD 0
.IP g
Genome
.IP b
Big sequence
.IP m
MegaReport
.IP t
Include Tag
.IP s
Tag for Superuser
.PD
.RE
.TP
\fB\-R\fP
Remote fetching from ID
.TP
\fB\-S\fP
Summary report
.TP
\fB\-T\fP
Use threads
.TP
\fB\-X\fP\ \fItests\fP
EXpand report categories (comma-delimited list of test names as listed
below or ALL).
.TP
\fB\-Z\fP
Remote CDS Product Fetch
.TP
\fB\-a\fP\ \fIstr\fP
ASN.1 type
.RS
.PD 0
.IP a
Any (default)
.IP e
seq-Entry
.IP b
Bioseq
.IP s
bioseq-Set
.IP m
seq-subMit
.IP t
baTch bioseq-set
.IP u
batch seq-sUbmit
.PD
.RE
.TP
\fB\-b\fP
Batch file is Binary
.TP
\fB\-c\fP
Batch file is Compressed
.TP
\fB\-d\fP\ \fIstr\fP
Disable tests (comma-delimited list of test names as listed below).
.TP
\fB\-e\fP\ \fIstr\fP
Enable tests (comma-delimited list of test names as listed below).
.TP
\fB\-f\fP
Use Feature table output format
.TP
\fB\-i\fP\ \fIfilename\fP
Single input file (standard input by default)
.TP
\fB\-k\fP
Local fetching
.TP
\fB\-l\fP
Load components in advance
.TP
\fB\-o\fP\ \fIfilename\fP
Single output file
.TP
\fB\-p\fP\ \fIpath\fP
Path to ASN.1 files
.TP
\fB\-r\fP\ \fIdir\fP
Output directory
.TP
\fB\-s\fP\ \fIext\fP
Output file Suffix (\fB.dr\fP by default)
.TP
\fB\-t\fP
Big Test Set
.TP
\fB\-u\fP
Recurse
.TP
\fB\-w\fP\ \fIfilename\fP
Suspect product rule filename
.TP
\fB\-x\fP\ \fIstr\fP
File selection substring (\fB.sqn\fP by default)
.SS AVAILABLE TESTS
.P
.ad l
.nh
MISSING_GENES, EXTRA_GENES, MISSING_LOCUS_TAGS, DUPLICATE_LOCUS_TAGS,
BAD_LOCUS_TAG_FORMAT, INCONSISTENT_LOCUS_TAG_PREFIX, NON_GENE_LOCUS_TAG,
DISC_COUNT_NUCLEOTIDES, MISSING_PROTEIN_ID, INCONSISTENT_PROTEIN_ID,
FEATURE_LOCATION_CONFLICT, GENE_PRODUCT_CONFLICT, DUPLICATE_GENE_LOCUS,
EC_NUMBER_NOTE, PSEUDO_MISMATCH, JOINED_FEATURES, OVERLAPPING_GENES,
OVERLAPPING_CDS, CONTAINED_CDS, RNA_CDS_OVERLAP, SHORT_CONTIG,
INCONSISTENT_BIOSOURCE, SUSPECT_PRODUCT_NAMES, DISC_PRODUCT_NAME_TYPO,
DISC_PRODUCT_NAME_QUICKFIX, INCONSISTENT_SOURCE_DEFLINE,
PARTIAL_CDS_COMPLETE_SEQUENCE, EC_NUMBER_ON_UNKNOWN_PROTEIN,
TAX_LOOKUP_MISSING, TAX_LOOKUP_MISMATCH, SHORT_SEQUENCES, SUSPECT_PHRASES,
DISC_SUSPICIOUS_NOTE_TEXT, COUNT_TRNAS, FIND_DUP_TRNAS, FIND_BADLEN_TRNAS,
FIND_STRAND_TRNAS, COUNT_RRNAS, FIND_DUP_RRNAS, RNA_NO_PRODUCT,
TRANSL_NO_NOTE, NOTE_NO_TRANSL, TRANSL_TOO_LONG, CDS_TRNA_OVERLAP,
COUNT_PROTEINS, DISC_FEAT_OVERLAP_SRCFEAT, MISSING_GENPRODSET_PROTEIN,
DUP_GENPRODSET_PROTEIN, MISSING_GENPRODSET_TRANSCRIPT_ID,
DISC_DUP_GENPRODSET_TRANSCRIPT_ID, DISC_PERCENT_N, N_RUNS, ZERO_BASECOUNT,
ADJACENT_PSEUDOGENES, NO_ANNOTATION, DISC_INFLUENZA_DATE_MISMATCH,
DISC_SHORT_INTRON, DISC_MISSING_VIRAL_QUALS, DISC_SRC_QUAL_PROBLEM,
DISC_MISSING_SRC_QUAL, DISC_DUP_SRC_QUAL, DISC_DUP_SRC_QUAL_DATA,
DISC_HAPLOTYPE_MISMATCH, DISC_FEATURE_MOLTYPE_MISMATCH,
DISC_CDS_WITHOUT_MRNA, DISC_EXON_INTRON_CONFLICT, DISC_FEATURE_COUNT,
DISC_SPECVOUCHER_TAXNAME_MISMATCH, DISC_GENE_PARTIAL_CONFLICT,
DISC_FLATFILE_FIND_ONCALLER, DISC_CDS_PRODUCT_FIND, DISC_DUP_DEFLINE,
DUP_DISC_ATCC_CULTURE_CONFLICT, DISC_USA_STATE, DISC_INCONSISTENT_MOLTYPES,
DISC_SUBMITBLOCK_CONFLICT, DISC_POSSIBLE_LINKER,
DISC_TITLE_AUTHOR_CONFLICT, DISC_BAD_GENE_STRAND,
DISC_MAP_CHROMOSOME_CONFLICT, DISC_RBS_WITHOUT_GENE,
DISC_CITSUBAFFIL_CONFLICT, DISC_REQUIRED_CLONE, DISC_SOURCE_QUALS_ASNDISC,
DISC_mRNA_ON_WRONG_SEQUENCE_TYPE, DISC_RETROVIRIDAE_DNA,
DISC_CHECK_AUTH_CAPS, DISC_CHECK_RNA_PRODUCTS_AND_COMMENTS,
DISC_MICROSATELLITE_REPEAT_TYPE, DISC_MITOCHONDRION_REQUIRED,
DISC_UNPUB_PUB_WITHOUT_TITLE, DISC_QUALITY_SCORES,
DISC_INTERNAL_TRANSCRIBED_SPACER_RRNA, DISC_PARTIAL_PROBLEMS,
DISC_BACTERIAL_PARTIAL_NONEXTENDABLE_PROBLEMS,
DISC_BACTERIAL_PARTIAL_NONEXTENDABLE_EXCEPTION, DISC_SUSPECT_RRNA_PRODUCTS,
DISC_SUSPECT_MISC_FEATURES, DISC_BACTERIA_MISSING_STRAIN,
DISC_MISSING_DEFLINES, DISC_MISSING_AFFIL,
DISC_BACTERIA_SHOULD_NOT_HAVE_ISOLATE, DISC_BACTERIA_SHOULD_NOT_HAVE_MRNA,
DISC_CDS_HAS_NEW_EXCEPTION, DISC_TRINOMIAL_SHOULD_HAVE_QUALIFIER,
DISC_METAGENOMIC, DISC_METAGENOME_SOURCE, ONCALLER_GENE_MISSING,
ONCALLER_SUPERFLUOUS_GENE, DISC_SHORT_RRNA, ONCALLER_CHECK_AUTHORITY,
ONCALLER_CONSORTIUM, ONCALLER_STRAIN_CULTURE_COLLECTION_MISMATCH,
ONCALLER_MULTISRC, ONCALLER_MULTIPLE_CULTURE_COLLECTION,
DISC_SEGSETS_PRESENT, DISC_NONWGS_SETS_PRESENT, DISC_FEATURE_LIST,
DISC_CATEGORY_HEADER, DISC_MISMATCHED_COMMENTS,
DISC_STRAIN_TAXNAME_MISMATCH, DISC_HUMAN_HOST,
DISC_BAD_BACTERIAL_GENE_NAME, TEST_BAD_GENE_NAME, ONCALLER_ORDERED_LOCATION,
ONCALLER_COMMENT_PRESENT, ONCALLER_DEFLINE_ON_SET,
ONCALLER_HIV_RNA_INCONSISTENT, SHORT_PROT_SEQUENCES, TEST_EXON_ON_MRNA,
TEST_HAS_PROJECT_ID, ONCALLER_HAS_STANDARD_NAME,
ONCALLER_MISSING_STRUCTURED_COMMENTS, DISC_REQUIRED_STRAIN,
MISSING_GENOMEASSEMBLY_COMMENTS, DISC_BACTERIAL_TAX_STRAIN_MISMATCH,
TEST_CDS_HAS_CDD_XREF, TEST_UNUSUAL_NT, TEST_LOW_QUALITY_REGION,
TEST_ORGANELLE_NOT_GENOMIC, TEST_UNWANTED_SPACER, TEST_ORGANELLE_PRODUCTS,
TEST_SP_NOT_UNCULTURED, TEST_BAD_MRNA_QUAL, TEST_UNNECESSARY_ENVIRONMENTAL,
TEST_UNNECESSARY_VIRUS_GENE, TEST_UNWANTED_SET_WRAPPER, TEST_MISSING_PRIMER,
TEST_UNUSUAL_MISC_RNA, TEST_AMPLIFIED_PRIMERS_NO_ENVIRONMENTAL_SAMPLE,
TEST_DUP_GENES_OPPOSITE_STRANDS, TEST_SMALL_GENOME_SET_PROBLEM,
TEST_OVERLAPPING_RRNAS, TEST_MRNA_SEQUENCE_MINUS_STRAND_FEATURES,
TEST_TAXNAME_NOT_IN_DEFLINE, TEST_COUNT_UNVERIFIED, SHOW_TRANSL_EXCEPT,
SHOW_HYPOTHETICAL_CDS_HAVING_GENE_NAME, TEST_DEFLINE_PRESENT,
TEST_MRNA_OVERLAPPING_PSEUDO_GENE, FIND_OVERLAPPED_GENES,
DISC_BIOMATERIAL_TAXNAME_MISMATCH, DISC_CULTURE_TAXNAME_MISMATCH,
DISC_CHECK_AUTH_NAME, NON_RETROVIRIDAE_PROVIRAL, RNA_PROVIRAL,
SHORT_SEQUENCES_200, DISC_10_PERCENTN, N_RUNS_14, MOLTYPE_NOT_MRNA,
TECHNIQUE_NOT_TSA, MISSING_STRUCTURED_COMMENT, MISSING_PROJECT,
MULTIPLE_CDS_ON_MRNA, DUP_DISC_CBS_CULTURE_CONFLICT,
DIVISION_CODE_CONFLICTS, RRNA_NAME_CONFLICTS, EUKARYOTE_SHOULD_HAVE_MRNA,
MRNA_SHOULD_HAVE_PROTEIN_TRANSCRIPT_IDS, ONCALLER_COUNTRY_COLON,
ONCALLER_BIOPROJECT_ID, ONCALLER_STRAIN_TAXNAME_CONFLICT
.hy
.ad b
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.BR asnval (1),
.BR cleanasn (1).
